name: Flutter CI

on: push

jobs: 
  build-and-test: 
    runs-on: ubuntu-latest
    steps:
    # checkout code
    - name: Checkout code
      uses: actions/checkout@v1 
    - name: Setup Java (12.x)
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Install Flutter (stable)
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable' 
    - name: Install dependencies
      run: flutter pub get
    - name: Build AOT
      run: flutter build aot
    - name: Analyze code
      run: flutter analyze
    # Run tests
    # - run: flutter test
